### ISSUE TITLE
Unable to tap dtan4/tools

### ISSUE THREAD

**Issue by nic-hima** [dtan4/homebrew-dtan4#23]
Seems that your previous CI runs https://github.com/dtan4/homebrew-tools/actions have picked this issue up before.

Unfortunately it seems a couple errors potentially coming from homebrew regarding lines: 
- https://github.com/dtan4/homebrew-tools/blob/master/Formula/ghrls.rb#L9
- https://github.com/dtan4/homebrew-tools/blob/master/Formula/s3url.rb#L6

Unfortunately I am NOT a `brew` expert @dtan4 , otherwise I would try to look into & test this. I really hope you can get this figured out soon.

Local env & error for me:
```
$ brew -v
Homebrew 3.4.2
Homebrew/homebrew-core (git revision 531ba36bcba; last commit 2022-03-15)
Homebrew/homebrew-cask (git revision d5f462a6eb; last commit 2022-03-15)

$ brew tap dtan4/tools
...
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/dtan4/homebrew-tools/Formula/ghrls.rb
ghrls: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the dtan4/tools tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/dtan4/homebrew-tools/Formula/ghrls.rb:9

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/dtan4/homebrew-tools/Formula/s3url.rb
s3url: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the dtan4/tools tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/dtan4/homebrew-tools/Formula/s3url.rb:6

Error: Cannot tap dtan4/tools: invalid syntax in tap!
```

**Comment by technodrome** [comment]
Same issue here. Any update?

**Comment by dtan4** [comment]
Fixed at https://github.com/dtan4/homebrew-tools/pull/24

**Comment by nic-hima** [comment]
Thank you @dtan4  👍
